### ISSUE TITLE
XCode: "main does not have an architecture that IPhone 7 Plus can execute"

### ISSUE THREAD

**Issue by joeblew99** [xlab/ios-go#3]
thanks for previous fix.

I did a go get -u -v and built the example using make.
It now pops up a dialog asking for keychain access and the build says "success".
Yeah !!

Then i open xcode and try to run the simulator.
Its says "main does not have an architecture that IPhone 7 Plus can execute".
I am a newbie on Xcode :)

**Comment by joeblew99** [comment]
did some googling.

In xcode change the build > architecture setting:
Base SDK is set to "Latest IOS (IOS 10.3)"
Changed it to others but nothing worked for me.

Here is the section expanded as  screenshot :)
![screen shot 2017-07-04 at 09 29 17](https://user-images.githubusercontent.com/11999859/27819618-58ac864e-609b-11e7-8783-b21e5dcdbfcf.png)

**Comment by xlab** [comment]
XCode cannot compile binaries for Go, the scheme works as this: you re-compile your binary using Makefile, XCode creates a package with it. Try to revisit the commands in Makefile and run them by hand or with `make`.

**Comment by xlab** [comment]
Ok, I'm getting the same issue now, probably caused by recent XCode update.

> Its says "main does not have an architecture that IPhone 7 Plus can execute".

**UPD:** wait a second, I never tried to run this on an emulator! You cannot have accelerated graphics and access to Metal using simulator. Use a real device instead.
